name: Update Submodule

on:
  repository_dispatch:
    types: [submodule-updated]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository A
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Force update submodule B
        run: |
          # 进入子模块所在的目录，根据之前的日志，它叫 'content'
          cd content
          # 从远程仓库拉取最新的信息
          git fetch
          # 强行将本地重置为远程 main 分支的最新状态
          git reset --hard origin/main
          # 增加下面这一行，用来同步嵌套的子模块
          git submodule update --init --recursive

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in submodule. Committing and pushing..."
            git add .
            git commit -m "chore: Automatically update submodule from repo B"
            git push
          else
            echo "No changes in submodule."
          fi